"""initial schema

Built from the SQLAlchemy metadata rather than a hand-transcribed DDL copy.
The models carry dialect variants (JSONB on PostgreSQL, JSON on SQLite); a
transcribed migration would silently drift from them. Later migrations should
be normal autogenerated diffs.

Revision ID: 0001
Revises:
"""
from __future__ import annotations

from alembic import op

from app.models import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
